### ISSUE TITLE
앱 출시 여부 질문

### ISSUE THREAD

**Issue by rlarjsdn3** [JeeSeongDeok/valorantapp#4]
안녕하세요. 연습삼아 발로란트를 주제로 프로젝트 중인 학생입니다. 플레이 스토어에 앱이 게시되어 있지 않은 걸로 보의는데, DMCA 이슈로 닫힌 상태인가요? 

 다른 앱은 여전히 서비스 중인데, 앱을 내리신 이유가 궁금합니다.

**Comment by JeeSeongDeok** [comment]
@rlarjsdn3 앱 개발만 하고 플레이 스토어에는 올리지 않았어요.

앱 서비스를 제공할려면 서버를 열어야 하는데 저한테 부담이 커서 올리지 않았습니다.
